// Placeholder firebase_options.dart
// Replace this file with the one generated by `flutterfire configure` or
// `flutterfire cli` for your Firebase project. This placeholder allows the
// project to compile locally until you provide real Firebase configuration.

class DefaultFirebaseOptions {
  static const currentPlatform = _FirebaseOptions._empty();
}

class _FirebaseOptions {
  const _FirebaseOptions._empty();
}

